StackOverflow/StackOverflow/Models/Question.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StackOverflow.Models
{
    public class Question
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string Header { get; set; }
        public string Content { get; set; }
        public User User { get; set; }
        public int UserID { get; set; }

        public ICollection<Answer> Answers { get; set; }
    }
}

StackOverflow/StackOverflow/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StackOverflow.DAO;
using StackOverflow.Data;
using StackOverflow.Models;

namespace StackOverflow.Controllers
{
    public class AnswersController : Controller
    {
        //private readonly SOContext _context;
        private readonly IAnswerDAO _answerDAO;

        public AnswersController(SOContext context,IAnswerDAO answerDAO)        {
            //_context = context;
            _answerDAO = answerDAO;
        }

        // GET: Answers
       /* public async Task<IActionResult> Index()
        {
            var stackOverflowContext = _context.Answers.Include(a => a.User);
            return View(await stackOverflowContext.ToListAsync());
        }
*/
        // GET: Answers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Answer answer = _answerDAO.GetAnswerById(id);            
            if (answer == null)
            {
                return NotFound();
            }

            return View(answer);
        }

        // GET: Answers/Create
        public IActionResult Create(string answer)
        {
            
            int questionId = (int)TempData["questionId"];
            int userId = (int)TempData["userId"];
            Answer answ = new Answer
            {
                Content = answer,
                UserID = userId,
                QuestionID = questionId                
            };
            _answerDAO.CreateAnswer(answ);            
            return RedirectToAction("Details", "Questions",new { id = questionId } );            
        }      

        // GET: Answers/Edit/5
      /*  public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var answer = await _context.Answers.FindAsync(id);
            if (answer == null)
            {
                return NotFound();
            }
            ViewData["UserID"] = new SelectList(_context.Set<User>(), "ID", "ID", answer.UserID);
            return View(answer);
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Content,Raiting,UserID")] Answer answer)
        {
            if (id != answer.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(answer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnswerExists(answer.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserID"] = new SelectList(_context.Set<User>(), "ID", "ID", answer.UserID);
            return View(answer);
        }

        // GET: Answers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var answer = await _context.Answers
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (answer == null)
            {
                return NotFound();
            }

            return View(answer);
        }

        // POST: Answers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var answer = await _context.Answers.FindAsync(id);
            _context.Answers.Remove(answer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnswerExists(int id)
        {
            return _context.Answers.Any(e => e.ID == id);
        }*/
    }
}

StackOverflow/StackOverflow/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StackOverflow.DAO;
using StackOverflow.Data;
using StackOverflow.Models;

namespace StackOverflow.Controllers
{
    public class QuestionsController : Controller
    {        
        private readonly IQuestionDAO _questionDAO;
        private readonly IAnswerDAO _answerDAO;
        public QuestionsController(IQuestionDAO questionDAO, IAnswerDAO answerDAO)
        {
            _questionDAO = questionDAO;
            _answerDAO = answerDAO;
        }

        // GET: Questions
        public async Task<IActionResult> Index()
        {   
            IEnumerable<Question> questions = _questionDAO.GetAllQuestions();
            ViewData["Greeting"] = TempData["userName"];
            return View(questions);            
        }

        // GET: Questions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            AQViewModel viewModel = new AQViewModel();            
            viewModel.Answers = _answerDAO.GetAnswersByQuestionId(id);            
            viewModel.Question = _questionDAO.GetQuestionById(id);
            
            TempData["questionId"] = id;
            return View(viewModel);             
        }

        // GET: Questions/Create
        public IActionResult Create()
        {  
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Question question)
        {
            if (ModelState.IsValid)
            {
                question.UserID = (int)TempData["userId"];
                _questionDAO.CreateQuestion(question);
                return RedirectToAction(nameof(Index));
            }           
            return View(question);
        }

        // GET: Questions/Edit/5
      /*  public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            //var question = await _context.Questions.FindAsync(id);
            Question question = _questionDAO.GetQuestionById(id);
            if (question == null)
            {
                return NotFound();
            }
            //ViewData["UserID"] = new SelectList(_context.Users, "ID", "ID", question.UserID);
            //ViewData["UserID"] = new SelectList(_questionDAO.GetAllQuestions, "ID", "ID", question.UserID);
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Header,Content,UserID")] Question question)
        {
            if (id != question.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(question);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionExists(question.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserID"] = new SelectList(_context.Users, "ID", "ID", question.UserID);
            return View(question);
        }*/

        // GET: Questions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var question = await _context.Questions.Include(q => q.User).FirstOrDefaultAsync(m => m.ID == id);
            Question question = _questionDAO.GetQuestionById(id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {   
            Question question = _questionDAO.GetQuestionById(id);
            _questionDAO.DeleteQuestion(question);
            return RedirectToAction(nameof(Index));
        }
    }
}

StackOverflow/StackOverflow/Views/Questions/Create.cshtml
@model StackOverflow.Models.Question

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Question</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Header" class="control-label"></label>
                <input asp-for="Header" class="form-control" />
                <span asp-validation-for="Header" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>                
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StackOverflow/StackOverflow/Views/Questions/Delete.cshtml
@model StackOverflow.Models.Question

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Header)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Header)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.ID)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

StackOverflow/StackOverflow/Views/Questions/Details.cshtml
@*@model StackOverflow.Models.Question*@
@model StackOverflow.Models.AQViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Question</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Question by
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Question.User.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Question.Header)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Question.Header)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Question.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Question.Content)
        </dd>

    </dl>
</div>
<div>
    <form asp-controller="Answers" asp-action="Create" method="get">
        <div class="form-group">
            <label  class="control-label">Your answer</label>
            <textarea name="answer"  class="form-control"></textarea>            
        </div>
        <div class="form-group">
            <input type="submit" value="Put answer" class="btn btn-primary" />
        </div>
    </form>
</div>
<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Answers
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Answers)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Content)
                    </td>

                    <td>
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.Question.ID">Edit</a> |*@
    <a asp-action="Index">Back to List</a>
</div>

StackOverflow/StackOverflow/Views/Questions/Edit.cshtml
@model StackOverflow.Models.Question

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Question</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Header" class="control-label"></label>
                <input asp-for="Header" class="form-control" />
                <span asp-validation-for="Header" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserID" class="control-label"></label>
                <select asp-for="UserID" class="form-control" asp-items="ViewBag.UserID"></select>
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StackOverflow/StackOverflow/Views/Questions/Index.cshtml
@model IEnumerable<StackOverflow.Models.Question>

@{
    ViewData["Title"] = "Index";
}

<h1>Welcome @ViewData["Greeting"]</h1>

<p>
    <a asp-action="Create">Add new question</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
               Questions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Header)
                </td>               
                
                <td>                   
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>